### ISSUE TITLE
the brew version is not linked to the latest Master

### ISSUE THREAD

**Issue by EngRaff92** [YosysHQ/sby#124]
Running into this error again "No such command: dffunmap" on Mac. The only I could run Yosys is by installing it using brew. Cloning and running from the Master gives me tuns of issues (libraries not found and something that needs to be changed in the Makefile). Is there a way to release the latest Master I can see the latest release the pointing to the 0.9 stable. Sorry for this but I cannot make Yosys working at moment, I'll try out few times more

**Comment by nakengelhardt** [comment]
SBY generally requires having a matching version of Yosys installed, as it calls Yosys commands in the background which can change as Yosys evolves. The brew is not maintained by any of us so we have no influence on the versioning there.  

However we now have [OSS CAD Suite downloads](https://github.com/YosysHQ/oss-cad-suite-build/releases/latest) for macOS as well, which bundles yosys, sby, and all supported solvers. Installing this will avoid any problems of mismatched versions.
