### ISSUE TITLE
Error when running command `sby`

### ISSUE THREAD

**Issue by Wlfc912** [YosysHQ/sby#225]
I've followed [the installation guide](https://symbiyosys.readthedocs.io/en/latest/install.html#) to install all the necessary packages. But when I run the sby command - either `sby fifo.sby` as in the tutorial or just `sby`, I would get an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/sby", line 23, in <module>
    from sby_jobserver import SbyJobClient, process_jobserver_environment
  File "<fstring>", line 1
    (self.is_ready=)
                  ^
SyntaxError: invalid syntax
```

In the tutorial, it says if `sby` doesn't work then there must be a problem with the sby installation. But what problem exactly? I've googled a lot, and also tried installing OSS CAD Suite, but none of them helps. Could anyone help identify the cause of this error?

**Comment by jix** [comment]
I just merged a PR that resolves this Python 3.6 incompatibility (but have not checked for any other possible incompatibilities). I still recommend using at least Python 3.8 and we are planning to update the installation guide to reflect this.
