### ISSUE TITLE
Please add tags corresponding to Yosys releases

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/sby#229]
If I remember correctly, @clairexen mentioned that each Yosys release needs to be shipped together with the SymbiYosys master branch commit at the time of release. This however makes it difficult to build historical versions of Yosys, e.g. to bisect changes.

**Comment by mmicko** [comment]
This is now available https://github.com/YosysHQ/sby/tags

**Comment by whitequark** [comment]
Thanks! I meant also _historically_ but I guess there is always the YoWASP commit logs if you need that sort of information.
