### ISSUE TITLE
python error codes 

### ISSUE THREAD

**Issue by nipmac** [YosysHQ/sby#231]
Hello getting some error messages when I try to run 'sby', I am using ptyhon 3.8.13 as other users had mentioned that this is related to issue with python 3.6.  I am using CentOS 7, updating python further is problematic.

~ > sby
Traceback (most recent call last):
  File "/usr/local/bin/sby", line 22, in <module>
    from sby_core import SbyConfig, SbyTask, SbyAbort, SbyTaskloop, process_filename, dress_message
  File "/storage2/design_applications/APPS/yosys/bin/sby_core.py", line 19, in <module>
    import os, re, sys, signal, platform, click
ModuleNotFoundError: No module named 'click'
~ > python3 --version
Python 3.8.13
~ >

**Comment by nakengelhardt** [comment]
Oh right, we forgot to update the install docs to include the new dependency on `click` since #221.
Run `python3 -m pip install click` to get it (or use the prebuilt [OSS CAD Suite](https://github.com/YosysHQ/oss-cad-suite-build) binary packages, which come with all necessary dependencies).
