### ISSUE TITLE
Generating erroneous Yosys pass.

### ISSUE THREAD

**Issue by CrazybinaryLi** [YosysHQ/sby#305]
An erroneous Yosys script command 'hierarchy -smtcheck' was generated automatically.

**Comment by georgerennie** [comment]
There shouldn't be anything erroneous about `hierarchy -smtcheck`. It has been a feature of yosys since 0.19 released over 2 years ago.

Check that you are using up to date yosys/sby, and if you still have issues please provide a script to reproduce your issue
